export const Cites = {
  CITES_LOAD: "CITES_LOAD",
  CITES_SUCCESS: "CITES_SUCCESS"
};

export const Category = {
  CATEGORY_LOAD: "CATEGORY_LOAD",
  CATEGORY_SUCCESS: "CATEGORY_SUCCESS"
};

export const User = {
  USERLOGIN_LOAD: "USERLOGIN_LOAD",
  USERLOGIN_SUCCESS: "USERLOGIN_SUCCESS",
  USERREGISTER_LOAD: "USERREGISTER_LOAD",
  USERREGISTER_SUCCESS: "USERREGISTER_SUCCESS",
  USERLOGOUT: "USERLOGOUT",
  USER_ERRORS: "USER_ERRORS"
};
