export const Types = {
  SEARCH_FILTER_HOME_LOAD: "SEARCH_FILTER_HOME_LOAD",
  SEARCH_FILTER_HOME_LOAD_SUCCESS: "SEARCH_FILTER_HOME_LOAD_SUCCESS",
  SEARCH_FILTER_HOME_LOAD_FAIL: "SEARCH_FILTER_HOME_LOAD_FAIL",
  ACADEMYLIST_LOAD: "ACADEMYLIST_LOAD",
  ACADEMYLIST_LOAD_SUCCESS: "ACADEMYLIST_LOAD_SUCCESS",
  ACADEMYLIST_LOAD_FAIL: "ACADEMYLIST_LOAD_FAIL",
  ACADEMYDETAILS_LOAD: "ACADEMYDETAILS_LOAD:",
  ACADEMYDETAILS_LOAD_SUCCESS: "ACADEMYDETAILS_LOAD_SUCCESS:",
  ACADEMYDETAILS_LOAD_FAIL: "ACADEMYDETAILS_LOAD_FAIL:",
  PARTNERSCATEGORY_LOAD: "PARTNERSCATEGORY_LOAD:",
  PARTNERSCATEGORY_LOAD_SUCCESS: "PARTNERSCATEGORY_LOAD_SUCCESS:",
  PARTNERSCATEGORY_LOAD_FAIL: "PARTNERSCATEGORY_LOAD_FAIL:"
};


export const Cites = {
  CITES_LOAD: "CITES_LOAD",
  CITES_SUCCESS: "CITES_SUCCESS",
};

export const Distric ={
  DISTRIC_LOAD:"DISTRIC_LOAD",
  DISTRIC_SUCCESS:"DISTRIC_SUCCESS"
}